name: Code build and Deploy
on: push
jobs:
  CICDjobs:
  	env:
  	 imageName: "myjavaapp"
    runs-on: ubuntu-latest
    steps:
      - name: Clone the current repository on the runner
        uses: actions/checkout@v4
      - name: Setup Java 17 and maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven cloud
        run: mvn
      - name: Install Docker
        uses: docker/setup-docker-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.imageName }}:latest
      - name: Deploy the Image
        run: |
         docker run -d -P ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.imageName }}:latest
         docker ps -a 
